-- Basic config
require("core.mappings")
require("core.plugins")
require("core.colors")
require("core.configs")

-- Plugins config
require("plugins.telescope")
require("plugins.nvimtree")
require("plugins.lsp")
require("plugins.mason")
require("plugins.lint")
require("plugins.cmp")
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.autotag")
require("plugins.buffline")
require("plugins.catppuccin")
require("plugins.dashboard")
require("plugins.tokyonight")
require("plugins.luasnip")
require("plugins.leap")
require("plugins.formatter")
